"""PDF report (spec 5.8) — a discussion document for contractors.

Pure function: bytes in (images, estimate payload, metadata) → PDF bytes. Built with reportlab
so it runs anywhere without system libraries.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone

from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.services.taxonomy import HUMAN

_HOW_TO_USE = (
    "Share it with contractors as a common baseline: confirm the measured areas on "
    "site, agree on rates per line, and treat the wastage allowances as negotiable. "
    "Re-run the estimate in RenovAI after editing rates to keep everyone aligned."
)

TEAL = colors.HexColor("#0f766e")
GREY = colors.HexColor("#6b7280")


def _money(v: float, cur: str) -> str:
    # Base-14 PDF fonts (Helvetica) have no glyph for ₹/most currency symbols — they render
    # as black boxes. Use plain ASCII prefixes in the PDF; the web UI still shows real symbols.
    if cur == "INR":
        digits = f"{v:,.0f}".replace(",", "")
        head, tail = digits[:-3], digits[-3:]
        parts: list[str] = []
        while len(head) > 2:
            parts.insert(0, head[-2:])
            head = head[:-2]
        if head:
            parts.insert(0, head)
        grouped = ",".join(parts + [tail]) if len(digits) > 3 else digits
        return f"Rs. {grouped}"
    return f"{cur} {v:,.0f}"


def _img(data: bytes, max_w: float, max_h: float) -> Image:
    im = PILImage.open(io.BytesIO(data))
    w, h = im.size
    scale = min(max_w / w, max_h / h)
    return Image(io.BytesIO(data), width=w * scale, height=h * scale)


def build_report(
    *,
    project_name: str,
    design_name: str,
    currency: str,
    original_jpeg: bytes,
    render_jpeg: bytes | None,
    render_provider: str | None,
    estimate: dict,
    materials: list[dict],  # [{region_name, label, material_name, category, description}]
    owner_email: str,
) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title=f"Renovation estimate — {project_name}",
        author="RenovAI",
    )
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], alignment=TA_LEFT, textColor=TEAL, fontSize=20)
    h2 = ParagraphStyle("h2", parent=ss["Heading2"], textColor=TEAL, spaceBefore=10)
    body = ParagraphStyle("body", parent=ss["BodyText"], fontSize=9, leading=12)
    small = ParagraphStyle("small", parent=body, fontSize=7.5, leading=10, textColor=GREY)
    cell = ParagraphStyle("cell", parent=body, fontSize=8, leading=10)
    num_cell = ParagraphStyle("num_cell", parent=cell, alignment=2)  # right-aligned

    W = A4[0] - 32 * mm
    now = datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")
    story = [
        Paragraph("Exterior renovation — visual &amp; cost estimate", h1),
        Paragraph(
            f"<b>{project_name}</b> · design “{design_name}” · prepared {now} for {owner_email}",
            body,
        ),
        Paragraph(
            "Pre-construction planning document generated by RenovAI. Areas are estimated from a "
            "photograph; quantities and costs are advisory and not a binding quotation.",
            small,
        ),
        Spacer(1, 6),
    ]

    # Images
    story.append(Paragraph("1. Before and after", h2))
    imgs = [_img(original_jpeg, W / 2 - 4, 70 * mm)]
    caps = [Paragraph("Original photo", small)]
    if render_jpeg:
        imgs.append(_img(render_jpeg, W / 2 - 4, 70 * mm))
        caps.append(Paragraph(f"Redesigned (renderer: {render_provider or 'n/a'})", small))
    t = Table([imgs, caps], colWidths=[W / 2] * len(imgs))
    t.setStyle(
        TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("ALIGN", (0, 0), (-1, -1), "CENTER")])
    )
    story.append(t)

    # Materials
    story.append(Paragraph("2. Selected materials", h2))
    rows = [["Surface", "Type", "Material", "Notes"]]
    for m in materials:
        rows.append(
            [
                Paragraph(m["region_name"], cell),
                Paragraph(HUMAN.get(m["label"], m["label"]), cell),
                Paragraph(m["material_name"], cell),
                Paragraph(m.get("description", ""), cell),
            ]
        )
    t = Table(rows, colWidths=[30 * mm, 24 * mm, 45 * mm, W - 99 * mm], repeatRows=1)
    t.setStyle(_table_style())
    story.append(t)

    # Scale & areas
    sc = estimate.get("scale", {})
    story.append(Paragraph("3. Measurements", h2))
    method_txt = sc.get("method", "").replace("_", " ")
    conf_txt = sc.get("confidence", "?")
    ft_per_in = sc.get("ft_per_px", 0) * 12
    scale_line = (
        f"Scale: 1 px \u2248 {ft_per_in:.2f} in \u2014 derived from "
        f"<b>{method_txt}</b> (confidence: {conf_txt})."
    )
    story.append(Paragraph(scale_line, body))
    rows = [["Surface", "Type", "Area (sq ft)", "Length (ft)", "Method / notes"]]
    for s in estimate.get("surfaces", []):
        if s["label"] in ("window", "door") and not any(
            ln["region_id"] == s["region_id"] for ln in estimate["lines"]
        ):
            continue
        rows.append(
            [
                Paragraph(s["name"], cell),
                Paragraph(HUMAN.get(s["label"], s["label"]), cell),
                f"{s['area_sqft']:,.1f}",
                f"{s['length_ft']:,.1f}" if s.get("length_ft") else "—",
                Paragraph("; ".join([s["method"], *s.get("notes", [])]), cell),
            ]
        )
    t = Table(rows, colWidths=[30 * mm, 24 * mm, 22 * mm, 20 * mm, W - 96 * mm], repeatRows=1)
    t.setStyle(_table_style(num_cols=(2, 3)))
    story.append(t)

    # Quantities & costs
    story.append(PageBreak())
    story.append(Paragraph("4. Quantities and cost breakdown", h2))
    rows = [
        [
            "Surface",
            "Material",
            "Surface",
            "Quantity",
            "Mat. rate",
            "Lab. rate",
            "Material",
            "Labour",
            "Total",
        ]
    ]
    for ln in estimate["lines"]:
        qty = f"{ln['quantity']:,.2f} {ln['quantity_unit']}"
        if ln.get("packs") is not None and ln.get("pack_label"):
            qty += f"<br/>({ln['packs']} {ln['pack_label']})"
        rows.append(
            [
                Paragraph(ln["region_name"], cell),
                Paragraph(ln["material_name"], cell),
                Paragraph(f"{ln['surface']:,.1f} {ln['surface_unit']}", num_cell),
                Paragraph(qty, cell),
                Paragraph(f"{ln['material_rate']:,.0f}/{ln['quantity_unit']}", num_cell),
                Paragraph(f"{ln['labor_rate']:,.0f}/{ln['surface_unit']}", num_cell),
                Paragraph(_money(ln["material_cost"], currency), num_cell),
                Paragraph(_money(ln["labor_cost"], currency), num_cell),
                Paragraph(_money(ln["total"], currency), num_cell),
            ]
        )
    for c in estimate.get("categories", []):
        rows.append(
            [
                "",
                Paragraph(f"<b>{c['category'].title()} subtotal</b>", cell),
                "",
                "",
                "",
                "",
                Paragraph(_money(c["material_cost"], currency), num_cell),
                Paragraph(_money(c["labor_cost"], currency), num_cell),
                Paragraph(_money(c["total"], currency), num_cell),
            ]
        )
    rows.append(
        [
            "",
            Paragraph("<b>Grand total</b>", cell),
            "",
            "",
            "",
            "",
            Paragraph(_money(estimate["material_total"], currency), num_cell),
            Paragraph(_money(estimate["labor_total"], currency), num_cell),
            Paragraph(f"<b>{_money(estimate['grand_total'], currency)}</b>", num_cell),
        ]
    )
    cw = [22 * mm, 28 * mm, 16 * mm, 22 * mm, 15 * mm, 15 * mm]
    rest = (W - sum(cw)) / 3
    t = Table(rows, colWidths=cw + [rest] * 3, repeatRows=1)
    t.setStyle(_table_style())
    story.append(t)

    story.append(Paragraph("5. Assumptions and limitations", h2))
    for a in estimate.get("assumptions", []):
        story.append(Paragraph(f"• {a}", body))
    story.append(Spacer(1, 4))
    story.append(
        KeepTogether(
            [
                Paragraph("How to use this document", h2),
                Paragraph(_HOW_TO_USE, body),
            ]
        )
    )
    doc.build(story)
    return buf.getvalue()


def _table_style(num_cols: tuple[int, ...] = ()) -> TableStyle:
    st = [
        ("BACKGROUND", (0, 0), (-1, 0), TEAL),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d4d4d8")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f4f5")]),
    ]
    for c in num_cols:
        st.append(("ALIGN", (c, 1), (c, -1), "RIGHT"))
    return TableStyle(st)
