"""material quantity_unit

Revision ID: 86d1713d4b6a
Revises: 070a3256fb5f
Create Date: 2026-08-25 11:53:11.102301
"""

import sqlalchemy as sa

from alembic import op

revision = "86d1713d4b6a"
down_revision = "070a3256fb5f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("materials", sa.Column("quantity_unit", sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("materials", "quantity_unit")
    # ### end Alembic commands ###
